/**
 * Shared Print/PDF preview — used by every "print" action across schedU so the
 * output is standardized: institution logo + name + address + document title on
 * top, the schedU watermark + print date-time in the footer, a paper-saving
 * toggle, and a big Print button. Paper size + orientation are chosen in the
 * printer dialog.
 *
 * Print isolation + layout live in index.css under `.schedu-print-*`.
 */
import { useState, useEffect, type ReactNode } from 'react'
import { createPortal } from 'react-dom'
import { institutionInfo, SCHEDU_MARK, type ExportSheet } from '@/lib/exportData'

/** Institution header (always printed, foreground): logo + name + address + title + session. */
export function InstitutionHeader({ title, session }: { title: string; session?: string }) {
  const inst = institutionInfo()
  return (
    <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: 16, borderBottom: '2px solid #7C6FE0', paddingBottom: 10, marginBottom: 12 }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
        {inst.logo && <img src={inst.logo} alt="" style={{ height: 42, maxWidth: 120, objectFit: 'contain' }} />}
        <div>
          <div style={{ fontSize: 19, fontWeight: 800, letterSpacing: '-0.3px', color: '#13111E', lineHeight: 1.15 }}>{inst.name}</div>
          {inst.address && <div style={{ fontSize: 10.5, color: '#8B87AD', marginTop: 2, maxWidth: 360 }}>{inst.address}</div>}
        </div>
      </div>
      <div style={{ textAlign: 'right', flexShrink: 0 }}>
        <div style={{ fontSize: 14, fontWeight: 700, color: '#7C6FE0' }}>{title}</div>
        {session && <div style={{ fontSize: 11, color: '#8B87AD', marginTop: 2 }}>Session {session}</div>}
      </div>
    </div>
  )
}

/**
 * Footer: schedU watermark (free tier only, light, foreground) + the print
 * date/time rendered as a BACKGROUND graphic so it only prints when Chrome's
 * "Background graphics" option is enabled.
 */
export function PrintFooter() {
  const inst = institutionInfo()
  const dt = new Date().toLocaleString(undefined, { year: 'numeric', month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' })
  const dtSvg = `<svg xmlns='http://www.w3.org/2000/svg' width='340' height='14'><text x='340' y='11' text-anchor='end' font-family='Arial, sans-serif' font-size='9.5' fill='#94A3B8'>Printed: ${dt.replace(/&/g, '&amp;').replace(/</g, '&lt;')}</text></svg>`
  const dtBg = `url("data:image/svg+xml;utf8,${encodeURIComponent(dtSvg)}")`
  return (
    <div className="schedu-print-footer" style={{ display: 'flex', alignItems: 'flex-end', justifyContent: 'space-between', gap: 12, marginTop: 10, paddingTop: 6, borderTop: '1px solid #EEE' }}>
      {!inst.isPaid ? (
        <div style={{ display: 'flex', alignItems: 'center', gap: 6, opacity: 0.5 }}>
          <div style={{ width: 18, height: 18, borderRadius: 5, background: '#7C6FE0', display: 'flex', alignItems: 'center', justifyContent: 'center', WebkitPrintColorAdjust: 'exact' as any }}
            dangerouslySetInnerHTML={{ __html: SCHEDU_MARK }} />
          <div style={{ fontSize: 8.5, color: '#8B87AD' }}>Generated by sched<span style={{ color: '#7C6FE0', fontWeight: 700 }}>U</span> · schedu.bhusku.com</div>
        </div>
      ) : <span />}
      <div className="schedu-print-datetime" style={{ minWidth: 200, height: 14, backgroundImage: dtBg, backgroundRepeat: 'no-repeat', backgroundPosition: 'right bottom' }} />
    </div>
  )
}

/** Render one data sheet (array-of-arrays) as a titled table for printing. */
export function DataTable({ sheet }: { sheet: ExportSheet }) {
  const [head, ...body] = sheet.rows
  return (
    <div>
      <h2 className="schedu-data-h2">{sheet.name}</h2>
      <table className="schedu-data-table">
        {head && <thead><tr>{head.map((c, i) => <th key={i}>{String(c ?? '')}</th>)}</tr></thead>}
        <tbody>
          {body.length
            ? body.map((r, ri) => <tr key={ri}>{r.map((c, ci) => <td key={ci}>{String(c ?? '')}</td>)}</tr>)
            : <tr><td className="schedu-data-empty" colSpan={head?.length || 1}>No data</td></tr>}
        </tbody>
      </table>
    </div>
  )
}

export interface PrintItem { key: string; node: ReactNode }

/**
 * The shared preview overlay. Each item becomes one self-contained block
 * (institution header + content + footer) that the printer can pack onto a page
 * (paper-saving) or isolate one-per-page. Renders nothing when `open` is false.
 */
export function PrintPreview({ open, title, session, subtitle, items, onClose }: {
  open: boolean
  /** Document title shown on the right of every header. */
  title: string
  /** Academic session/year shown under the title (e.g. "2025-26"). */
  session?: string
  /** Secondary text in the toolbar (e.g. "Master Data · 4 tables"). */
  subtitle?: string
  items: PrintItem[]
  onClose: () => void
}) {
  const [paperSaving, setPaperSaving] = useState(true)

  useEffect(() => {
    if (!open) return
    document.body.setAttribute('data-print-doc', 'on')
    const onKey = (e: KeyboardEvent) => { if (e.key === 'Escape') onClose() }
    window.addEventListener('keydown', onKey)
    return () => { window.removeEventListener('keydown', onKey); document.body.removeAttribute('data-print-doc') }
  }, [open, onClose])

  if (!open) return null

  const doPrint = () => {
    // Margin only — the printer dialog owns paper size + orientation.
    let ps = document.getElementById('schedu-print-page') as HTMLStyleElement | null
    if (!ps) { ps = document.createElement('style'); ps.id = 'schedu-print-page'; document.head.appendChild(ps) }
    ps.textContent = `@page { margin: 10mm; }`
    window.print()
  }

  return createPortal(
    <div className="schedu-print-overlay">
      <div className="schedu-print-toolbar no-print">
        <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
          <span style={{ fontSize: 14, fontWeight: 700, color: '#13111E' }}>Print preview</span>
          {subtitle && <span style={{ fontSize: 12, color: '#8B87AD' }}>{subtitle}</span>}
        </div>
        <div style={{ display: 'flex', alignItems: 'center', gap: 14 }}>
          <label title="Pack as much onto each page as fits (saves paper). Off = one block per page."
            style={{ display: 'flex', alignItems: 'center', gap: 7, fontSize: 12, fontWeight: 600, color: '#4B5275', cursor: 'pointer', userSelect: 'none' }}>
            <input type="checkbox" checked={paperSaving} onChange={e => setPaperSaving(e.target.checked)} style={{ width: 16, height: 16, accentColor: '#7C6FE0', cursor: 'pointer' }} />
            🌱 Paper-saving mode
          </label>
          <button onClick={doPrint}
            style={{ display: 'flex', alignItems: 'center', gap: 8, padding: '11px 28px', borderRadius: 10, border: 'none', background: '#7C6FE0', color: '#fff', fontSize: 15, fontWeight: 700, cursor: 'pointer', boxShadow: '0 4px 14px rgba(124,111,224,0.4)' }}>
            🖨️ Print
          </button>
          <button onClick={onClose} title="Close (Esc)"
            style={{ width: 36, height: 36, borderRadius: 9, border: '1px solid #E5EBF5', background: '#fff', color: '#64748b', fontSize: 18, cursor: 'pointer', lineHeight: 1 }}>✕</button>
        </div>
      </div>

      <div className="schedu-print-scroll">
        <div className="schedu-print-root" data-saving={paperSaving ? 'true' : 'false'}>
          {items.map(it => (
            <div className="schedu-print-entity" key={it.key}>
              <InstitutionHeader title={title} session={session} />
              {it.node}
              <PrintFooter />
            </div>
          ))}
        </div>
      </div>

      <button className="schedu-print-fab no-print" onClick={doPrint}>🖨️ Print</button>
    </div>,
    document.body,
  )
}
