// Auto-generated by TanStack Router
// In a real project, run: npx tsr generate
// This file is committed and stays in sync with your routes/ folder

import { createRootRoute, createRoute, createRouter } from "@tanstack/react-router"

import { Route as rootRoute }       from "./routes/__root"
import { Route as IndexRoute }      from "./routes/index"
import { Route as WizardRoute }     from "./routes/wizard/index"
import { Route as TimetableRoute }  from "./routes/timetable"

const routeTree = rootRoute.addChildren([
  IndexRoute,
  WizardRoute,
  TimetableRoute,
])

export { routeTree }
