/**
 * Reusable export helpers — Excel (SheetJS, loaded globally via index.html) and
 * a branded Print/PDF document. Print renders a clean, standalone document
 * (schedU + bhusku + institution header, then the data tables) into a hidden
 * iframe and prints that — so the output never includes app chrome, toolbars,
 * buttons or scrollbars, and it fits the chosen paper size + orientation.
 */
import { useAuthStore } from '@/store/authStore'
import { useTimetableStore } from '@/store/timetableStore'

declare const XLSX: any

export interface ExportSheet {
  name: string
  /** Array-of-arrays: first row is the header. */
  rows: (string | number)[][]
}

export type PaperSize = 'A4' | 'A3' | 'Letter' | 'Legal'
export type Orientation = 'landscape' | 'portrait'

/** Download one or more sheets as a single .xlsx workbook. */
export function exportSheetsToXLSX(filename: string, sheets: ExportSheet[]): void {
  if (typeof XLSX === 'undefined') {
    alert('Excel export library is still loading — please try again in a moment.')
    return
  }
  const wb = XLSX.utils.book_new()
  for (const s of sheets) {
    const ws = XLSX.utils.aoa_to_sheet(s.rows.length ? s.rows : [['(no data)']])
    XLSX.utils.book_append_sheet(wb, ws, (s.name || 'Sheet').slice(0, 31))
  }
  XLSX.writeFile(wb, filename.endsWith('.xlsx') ? filename : `${filename}.xlsx`)
}

function esc(v: unknown): string {
  return String(v ?? '').replace(/[&<>"]/g, c => (
    { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c] as string
  ))
}

/** schedU mark (white "b" glyph + gold dot) for the print header. */
export const SCHEDU_MARK = `<svg width="22" height="22" viewBox="0 0 52 52" fill="none"><rect x="12" y="9" width="8" height="33" rx="4" fill="white"/><path d="M 20 22 C 23 14 40 15 40 30 C 40 45 23 46 20 42" stroke="white" stroke-width="8" fill="none" stroke-linecap="round"/><circle cx="39" cy="10" r="4.5" fill="#D4920E"/></svg>`

/**
 * Institution branding for print/PDF headers, read from the stores
 * (best-effort). `isPaid` controls whether the schedU footer watermark shows
 * (free tier = watermark; pro/enterprise = none).
 */
export function institutionInfo(): { name: string; logo?: string; address?: string; isPaid: boolean } {
  const user = useAuthStore.getState().user as any
  const cfg = useTimetableStore.getState().config as any
  const org = (useTimetableStore.getState() as any).organization
  const name =
    user?.schoolName || org?.name || cfg?.schoolName || cfg?.orgName || cfg?.institutionName || 'Your Institution'
  const logo = org?.logoUrl || cfg?.logoUrl || user?.logoUrl || undefined
  const address = org?.address || cfg?.address || user?.address || undefined
  const plan = (user?.plan ?? 'free') as string
  const isPaid = plan === 'pro' || plan === 'enterprise' || plan === 'paid'
  return { name, logo, address, isPaid }
}

/**
 * Print a branded document built from `sheets`. Each sheet renders as a titled
 * table. Hidden-iframe based, so no pop-up blocker and no app chrome. Paper
 * size + orientation are chosen in the printer dialog (we set @page margin
 * only), so they're no longer passed in.
 */
export function printSheets(
  sheets: ExportSheet[],
  opts: { title: string },
): void {
  const inst = institutionInfo()
  const today = new Date().toLocaleDateString(undefined, { year: 'numeric', month: 'short', day: 'numeric' })

  const tablesHtml = sheets.map(sh => {
    const [head, ...body] = sh.rows
    const thead = head ? `<thead><tr>${head.map(c => `<th>${esc(c)}</th>`).join('')}</tr></thead>` : ''
    const rows = body.length
      ? body.map(r => `<tr>${r.map(c => `<td>${esc(c)}</td>`).join('')}</tr>`).join('')
      : `<tr><td colspan="${head?.length || 1}" class="empty">No data</td></tr>`
    return `<section><h2>${esc(sh.name)}</h2><table>${thead}<tbody>${rows}</tbody></table></section>`
  }).join('')

  const headerHtml = `<div class="doc-header">
    <div class="brand">
      <div class="mark">${SCHEDU_MARK}</div>
      <div>
        <div class="by">By Bhusku</div>
        <div class="name">sched<span class="u">U</span></div>
      </div>
    </div>
    <div class="inst">
      ${inst.logo ? `<img src="${esc(inst.logo)}" alt="logo" />` : ''}
      <div>
        <div class="iname">${esc(inst.name)}</div>
        <div class="meta">${esc(opts.title)} · ${esc(today)}</div>
      </div>
    </div>
  </div>`

  const footerHtml = `<div class="doc-footer">Generated by schedU · schedu.bhusku.com</div>`

  // The branded header/footer must repeat on EVERY printed page regardless of
  // paper size or orientation. A layout table with thead=table-header-group +
  // tfoot=table-footer-group is the only reliable cross-browser way to do that;
  // the data tables live inside a single tbody cell and flow across pages.
  const html = `<!doctype html><html><head><meta charset="utf-8"><title>${esc(inst.name)} — ${esc(opts.title)}</title>
<style>
  @page { margin: 12mm; }
  * { box-sizing: border-box; }
  html, body { margin: 0; }
  body { font-family: 'Plus Jakarta Sans', Arial, Helvetica, sans-serif; color: #13111E; -webkit-print-color-adjust: exact; print-color-adjust: exact; }

  /* Page layout table: header repeats at top of every page, footer at bottom. */
  table.page { width: 100%; border-collapse: collapse; }
  table.page > thead { display: table-header-group; }
  table.page > tfoot { display: table-footer-group; }
  table.page > thead > tr > th,
  table.page > tbody > tr > td,
  table.page > tfoot > tr > td { padding: 0; border: 0; font-weight: 400; text-align: left; }

  .doc-header { display: flex; align-items: center; justify-content: space-between; gap: 16px; border-bottom: 2px solid #7C6FE0; padding: 0 0 10px; margin-bottom: 14px; }
  .brand { display: flex; align-items: center; gap: 10px; }
  .brand .mark { width: 34px; height: 34px; border-radius: 9px; background: #7C6FE0; display: flex; align-items: center; justify-content: center; }
  .brand .by { font-size: 8px; letter-spacing: 0.14em; text-transform: uppercase; color: #8B87AD; }
  .brand .name { font-size: 18px; font-weight: 800; letter-spacing: -0.3px; line-height: 1; }
  .brand .name .u { color: #7C6FE0; font-style: italic; }
  .inst { display: flex; align-items: center; gap: 10px; text-align: right; }
  .inst img { height: 34px; max-width: 120px; object-fit: contain; }
  .inst .iname { font-size: 16px; font-weight: 700; }
  .inst .meta { font-size: 11px; color: #8B87AD; }
  .doc-footer { padding-top: 8px; margin-top: 12px; border-top: 1px solid #E8E4FF; font-size: 9px; color: #8B87AD; text-align: center; }

  /* Data tables */
  .content h2 { font-size: 13px; margin: 14px 0 6px; color: #13111E; }
  .content section { page-break-inside: auto; }
  .content section:first-child h2 { margin-top: 0; }
  .content table { width: 100%; border-collapse: collapse; font-size: 10px; margin-bottom: 6px; }
  .content th, .content td { border: 1px solid #C9C3EE; padding: 4px 6px; text-align: left; vertical-align: top; }
  .content thead th { background: #EDE9FF; color: #13111E; font-weight: 700; }
  .content thead { display: table-header-group; }
  .content tbody tr:nth-child(even) { background: #FAFAFE; }
  .content td.empty { text-align: center; color: #8B87AD; font-style: italic; }
</style></head>
<body>
  <table class="page">
    <thead><tr><th>${headerHtml}</th></tr></thead>
    <tfoot><tr><td>${footerHtml}</td></tr></tfoot>
    <tbody><tr><td><div class="content">${tablesHtml}</div></td></tr></tbody>
  </table>
</body></html>`

  const iframe = document.createElement('iframe')
  iframe.style.cssText = 'position:fixed;right:0;bottom:0;width:0;height:0;border:0;'
  document.body.appendChild(iframe)
  const doc = iframe.contentWindow?.document
  if (!doc) { document.body.removeChild(iframe); return }
  doc.open()
  doc.write(html)
  doc.close()
  const cleanup = () => setTimeout(() => { try { document.body.removeChild(iframe) } catch { /* already gone */ } }, 500)
  iframe.contentWindow!.addEventListener('afterprint', cleanup)
  setTimeout(() => { iframe.contentWindow!.focus(); iframe.contentWindow!.print() }, 350)
}
